# Generated by Django 2.1.4 on 2018-12-09 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20181209_2251'),
        ('users', '0003_shopuser_order_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Item')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.Size')),
            ],
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shopuser',
            name='order_history',
        ),
        migrations.AddField(
            model_name='shopuser',
            name='shopping_cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.ShoppingCart'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
