# Generated by Django 2.1.4 on 2018-12-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_embed_code', models.TextField(verbose_name='Playlist Embed Code')),
            ],
        ),
    ]
