# Generated by Django 2.1.4 on 2018-12-07 08:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyplaylist',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 12, 7, 8, 13, 0, 22967, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='spotifyplaylist',
            name='name',
            field=models.CharField(blank=True, default='Recomendaciones musicales', max_length=50),
        ),
    ]
