# Generated by Django 2.1.4 on 2018-12-07 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181207_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifyplaylist',
            old_name='spotify_embed_code',
            new_name='embed_code',
        ),
    ]
