# Generated by Django 2.1.4 on 2018-12-07 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181207_0820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spotifyplaylist',
            options={'managed': False},
        ),
    ]
