# Generated by Django 2.1.4 on 2018-12-09 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20181207_0823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spotifyplaylist',
            options={},
        ),
    ]
